name: Calibre Full Server Docker Image CI

on:
  pull_request:
    types: [closed]
    branches: [master]
  watch:
    types: [started]
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/calibre-fullserver
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create image Flag
        run: |
          export FLAG=$(date +%s)
          echo "::set-env name=FLAG::$FLAG"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
        #  platforms: all
          platforms: linux/arm64,linux/arm/v7 
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      
      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@34d5f75b0d6d0d22f06d83acf2fa1b144409ec83
        uses: docker/login-action@v1.4.1
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.DOCKER_REGISTRY_URL }} # optional
          # Username used to log against the Docker registry
          username: ${{ env.DOCKER_USERNAME }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ env.DOCKER_PASSWORD }} 
          # Log out from the Docker registry at the end of a job
          logout: true # optional, default is true

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
        uses: docker/build-push-action@v2
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ${{ env.DOCKER_USERNAME }} # optional
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ env.DOCKER_PASSWORD }} # optional
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ${{ env.DOCKER_REGISTRY_URL }} # optional
          # Docker repository to tag the image with
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
          tags: latest, ${{ env.FLAG }} # optional
          # Path to the build context
          path: . # optional, default is .
          # Path to the Dockerfile (Default is '{path}/Dockerfile')
          dockerfile: ./Dockerfile # optional
          # Always attempt to pull a newer version of the image
          #always_pull: # optional
          # Comma-delimited list of build-time variables
          #build_args: # optional
          # Comma-delimited list of labels to add to the built image
          #labels: # optional
          # Whether to push the image
          push: true # optional, default is true
